/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-08-23 15:37:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProductView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/customize.css\">\r\n");
      out.write("    <!-- Add icon library -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <title>Add Product - Mobile Store</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container p-5 my-3 bg-light\">\r\n");
      out.write("    	");
 
    		String username = (String) request.getAttribute("username");
    		if (username != null) {
    	
      out.write("\r\n");
      out.write("    	<a class=\"btn btn-danger float-right\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\"><i class=\"fa fa-sign-out\"></i> Log out</a>\r\n");
      out.write("    	");

    		}
    	
      out.write("\r\n");
      out.write("        <a class=\"btn float-right border mr-2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"><i class=\"fa fa-home\"></i> Home</a>\r\n");
      out.write("        <h1>Add Product</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container p-3\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-11\">\r\n");
      out.write("                Add new product\r\n");
      out.write("                <hr>\r\n");
      out.write("                <form id='add-product-form' method=\"POST\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addProduct\" enctype=\"multipart/form-data\">\r\n");
      out.write("                    <div class=\"form-group row ml-5\">\r\n");
      out.write("                      <label for=\"productName\" class=\"col-sm-2 col-form-label text-right\">Product Name</label>\r\n");
      out.write("                      <div class=\"col-sm-4\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"name\" required>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row ml-5\">\r\n");
      out.write("                        <label for=\"unitPrice\" class=\"col-sm-2 col-form-label text-right\">Unit Price</label>\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                          <input type=\"number\" class=\"form-control\" name=\"price\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row ml-5\">\r\n");
      out.write("                        <label for=\"unitStock\" class=\"col-sm-2 col-form-label text-right\">Unit in Stock</label>\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                          <input type=\"number\" class=\"form-control\" name=\"instock\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row ml-5\">\r\n");
      out.write("                        <label for=\"description\" class=\"col-sm-2 col-form-label text-right\">Description</label>\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                          <textarea rows=\"2\" class=\"form-control\" name=\"description\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row ml-5\">\r\n");
      out.write("                        <label for=\"manufacturer\" class=\"col-sm-2 col-form-label text-right\">Manufacturer</label>\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" name=\"manufacturer\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row ml-5\">\r\n");
      out.write("                        <label for=\"category\" class=\"col-sm-2 col-form-label text-right\">Category</label>\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                          <input type=\"text\" class=\"form-control\" name=\"category\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row ml-5\">\r\n");
      out.write("                        <label class=\"col-sm-2 col-form-label text-right\">Condition</label>\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"radio\" name=\"condition\" value=\"New\" required>\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"radio-new\">New</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"radio\" name=\"condition\" value=\"Old\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"radio-old\">Old</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"radio\" name=\"condition\" value=\"Refurbished\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"radio-refur\">Refurbished</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row ml-5\">\r\n");
      out.write("                        <label for=\"product-image\" class=\"col-sm-2 col-form-label text-right\">Product Image File</label>\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                          <input type=\"file\" class=\"form-control\" name=\"product-image\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group row\">\r\n");
      out.write("                        <div class=\"col-sm-3\"></div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\" id=\"btn-submit-product\">Add Product</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
